options {
    directory "/homelab-data/state/bind9/cache";
    recursion no;
    allow-query { any; };
    dnssec-validation auto;
    listen-on { any; };
    listen-on-v6 { any; };
};

zone "homelab.local" IN {
    type master;
    file "/homelab-data/config/bind9/zones/db.homelab.local";
};
